# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/alphaUltimateTTT',
                'doc_host': 'https://mellamanelpoeta.github.io',
                'git_url': 'https://github.com/mellamanelpoeta/alphaUltimateTTT',
                'lib_path': 'alphaUltimateTTT'},
  'syms': {'alphaUltimateTTT.core': {'alphaUltimateTTT.core.foo': ('core.html#foo', 'alphaUltimateTTT/core.py')}}}
