# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Game/Python implementation/Move.ipynb.

# %% auto 0
__all__ = ['Move']

# %% ../nbs/Game/Python implementation/Move.ipynb 3
#Copyright 2024 Gerardo Guerrero

from .constants import X_STATE_VALUE, O_STATE_VALUE

class Move:
    def __init__(self,
                symbol: int, # X_STATE_VALUE = 1 or O_STATE_VALUE = 2
                index: int): # int from 0 to 80
        '''A move contains the symbol (represented as an int) and the index (int from 0 to 80) where the symbol will be placed.'''
        self.symbol = symbol  # X_STATE_VALUE or O_STATE_VALUE
        self.index = index  # int from 0 to 80

    def __str__(self):
        output = '{cls}(symbol={symbol}, index={index})'
        output = output.format(
            cls='Move',
            symbol={X_STATE_VALUE: 'X', O_STATE_VALUE: 'O'}[self.symbol],
            index=self.index,
        )
        return output
